### ISSUE TITLE
feature request - add element snippet support

### ISSUE THREAD

**Issue by rtpHarry** [Hazzamanic/orchardizer#15]
Since 1.10 the layout element snippets have been expanded and you can have a supporting manifest file to define their metadata and make them into parameterized snippets.

I can pull the links together for more info if you're not already aware of it.

**Comment by Hazzamanic** [comment]
This sounds reasonable.

I have just skimmed this: http://www.ideliverable.com/blog/parameterized-snippets

I cant see the manifest info there, is there some docs I can take a look at?

**Comment by rtpHarry** [comment]
not really much in the way of docs that have been published but there was something sipke included in an earlier commit and then removed as it was beyond the scope of that pr:

# Layouts
The Layouts module enables users to visually add layout and content elements to a canvas.

## Snippets
Snippets are elements who are dynamically discovered based on shapes that follow a certain naming convention.
The naming convention is that all shapes ending in "Snippet" are harvested as a snippet element. For example, MyLogoSnippet.cshtml will be registered as an element called "My Logo".

### Parameterized Snippets
In addition to snippet files, you can provide a snippet manifest file for a particular snippet using YAML.
The naming convention of the snippet manifest file is to use the same name as the shape template, but suffixed with .txt. For example: "MyLogoSnippet.txt".

This manifest file declares meta information about your snippet, such as a display name, description, toolbox icon, and most importantly, fields.

Fields declared in the manifest will appear as configurable fields for users when adding the snippet to the canvas.
The snippet shape template itself can then reference these fields and output the user-provided values.

The following is a sample snippet manifest file:

```yaml
DisplayName: My Logo
ToolboxIcon: \uf1c5
Fields:
  - Name: ImageUrl
    Type: Url
    DisplayName: Image URL
    Description: The URL to your logo.

  - Name: Payoff
    Type: Text
    DisplayName: Payoff
    Description: The payoff to display next to your logo.
```


However there are some things to note:

  - only "text" type has shipped so for the `Type`
  - at the moment the snippet displayname and toolboxicon (first two properties) are not read (I do have a PR in progress with it though, just hit a bug at the moment with a unicode issue)
